[project]
name = "eth-qhack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bloqade>=0.24.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
